# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

image: python:3.10

stages:
- lint
- test
- build
- pages

before_script:
  - pip install --upgrade pip

lint:
  stage: lint
  script:
    - pip install pre-commit
    - pre-commit run --all-files

fast_tests:
  stage: test
  script:
    - pip install .[dev]
    - PYTHONPATH=src pytest tests -m "not slow" --cov=mondAI --cov-report=term-missing --cov-report=xml --cov-config=pyproject.toml
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

all_tests:
  stage: test
  script:
    - pip install .[dev,comparison]
    - PYTHONPATH=src pytest tests --cov=mondAI --cov-report=term-missing --cov-report=xml --cov-config=pyproject.toml
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:
  stage: build
  script:
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/

pages:
  stage: pages
  script:
    # Install dependencies
    - pip install .[dev]
    # Build HTML docs
    - cd docs
    - make html
    # Copy the generated HTML to the public folder
    - cd ..
    - mkdir -p public
    - cp -r docs/build/html/* public/
  artifacts:
    paths:
      - public
  only:
    - /^main$|^develop$|^release-.*$/  # build docs only on main, develop or release branches


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .venv/
    - ~/.cache/pip/
