[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "mondAI"
version = "0.0.1"
description = "Image quality metrics for medical imaging"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Division of Intelligent Medical Systems (IMSY), German Cancer Research Center (DKFZ)", email = "your.email@example.com" },
]
requires-python = ">=3.10"

dependencies = [
    "torch>=2.10", # BSD-3-Clause
    "numpy",       # BSD-3-Clause and MIT
]

[project.optional-dependencies]
dev = [
    "pytest",              # MIT
    "pytest-cov",          # MIT
    "pytest-regressions",  # MIT
    "pre-commit",          # MIT
    "ruff",                # MIT
    "mypy",                # MIT
    "sphinx",              # BSD-2-Clause
    "pydata-sphinx-theme", # BSD-3-Clause
    "myst-parser",         # BSD-2-Clause
    "scikit-image",        # BSD-3-Clause
    "pooch",               # BSD-3-Clause
    "matplotlib",          # PSF-2.0
]
comparison = [
    "scikit-learn==1.7.2", # BSD-3-Clause
    "tensorflow==2.16.1",  # Apache-2.0
    "monai==1.5.1",        # Apache-2.0
    "piq==0.8.0",          # Apache-2.0
    "deepinv==0.4.0",      # BSD-3-Clause
    "piqa==1.3.2",         # MIT
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra -q"
[tool.coverage.run]
omit = [
    'src/mondAI/metrics/full_reference/haarpsi_original.py',
    'src/mondAI/metrics/full_reference/haarpsi_ideal_iqa.py',
    'src/mondAI/metrics/full_reference/compare_haarpsi.py',
    'src/mondAI/metrics/.metric_template.py',
]


[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "B"]

[tool.docformatter]
wrap-summaries = 87
wrap-descriptions = 87
blank = true
pre-summary-newline = false
make-summary-multi-line = false

[tool.mypy]
strict = true
disallow_untyped_decorators = false
